automation:
  alias: B2500PKG_B04_Voltage_Discovery
  triggers:
    - topic: hame_energy/B2500_04/CD13
      trigger: mqtt
  conditions: []
  actions:
    - variables:
        payload: "{{ trigger.payload }}"
    - if:
        - condition: template
          value_template: "{{ 'a0=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a0/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle01",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a0=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle01",
                "object_id": "b2500_04_zelle01",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a1=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a1/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle02",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a1=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle02",
                "object_id": "b2500_04_zelle02",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a2=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a2/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle03",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a2=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle03",
                "object_id": "b2500_04_zelle03",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a3=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a3/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle04",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a3=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle04",
                "object_id": "b2500_04_zelle04",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a4=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a4/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle05",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a4=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle05",
                "object_id": "b2500_04_zelle05",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a5=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a5/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle06",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a5=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle06",
                "object_id": "b2500_04_zelle06",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a6=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a6/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle07",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a6=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle07",
                "object_id": "b2500_04_zelle07",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a7=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a7/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle08",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a7=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle08",
                "object_id": "b2500_04_zelle08",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a8=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a8/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle09",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a8=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle09",
                "object_id": "b2500_04_zelle09",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'a9=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_a9/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle10",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('a9=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle10",
                "object_id": "b2500_04_zelle10",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'aa=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_aa/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle11",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('aa=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle11",
                "object_id": "b2500_04_zelle11",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'ab=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_ab/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle12",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('ab=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle12",
                "object_id": "b2500_04_zelle12",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'ac=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_ac/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle13",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('ac=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle13",
                "object_id": "b2500_04_zelle13",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'ad=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_ad/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle14",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('ad=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle14",
                "object_id": "b2500_04_zelle14",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'ae=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_ae/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle15",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('ae=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle15",
                "object_id": "b2500_04_zelle15",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - if:
        - condition: template
          value_template: "{{ 'af=' in payload }}"
      then:
        - data:
            topic: homeassistant/sensor/b2500_04/voltage_af/config
            retain: true
            payload: |
              {% raw %} {
                "name": "B04 Zelle16",
                "state_topic": "hame_energy/B2500_04/CD13",
                "device_class": "voltage",
                "unit_of_measurement": "mV",
                "value_template": "{{ value.split('af=')[1].split(',')[0] }}",
                "unique_id": "sensor.b2500_04_zelle16",
                "object_id": "b2500_04_zelle16",
                "entity_category": "diagnostic"
              } {% endraw %}
          action: mqtt.publish
    - action: automation.turn_off
      metadata: {}
      data:
        stop_actions: false
      target:
        entity_id: automation.b2500pkg_b04_voltage_discovery
