automation:
  alias: Package by Martin0475 B2500_Respost_CD01_und_CD13_neue_Version
  description: ""
  triggers:
    - trigger: mqtt
      topic: hame_energy/+/device/+/ctrl
      payload: p1=
      value_template: "{{ value[0:3] }}"
      id: b2500_cd01
    - trigger: mqtt
      topic: hame_energy/+/device/+/ctrl
      payload: a0=
      value_template: "{{ value[0:3] }}"
      id: b2500_cd13
  conditions: []
  actions:
    - variables:
        speicher_nummer: >-
          {{ 'B2500_01' if trigger.topic == 'hame_energy/' +
          states('input_select.b2500_01_typ') + '/device/' +
          states('input_text.b2500_01_mac') + '/ctrl'
           else 'B2500_02' if trigger.topic == 'hame_energy/' +
          states('input_select.b2500_02_typ') + '/device/' + states('input_text.b2500_02_mac') + '/ctrl'
           else 'B2500_03' if trigger.topic == 'hame_energy/' +
          states('input_select.b2500_03_typ') + '/device/' + states('input_text.b2500_03_mac') + '/ctrl'
           else 'B2500_04' if trigger.topic == 'hame_energy/' +
          states('input_select.b2500_04_typ') + '/device/' + states('input_text.b2500_04_mac') + '/ctrl'
          else '0'}}
    - choose:
        - conditions:
            - condition: trigger
              id:
                - b2500_cd01
          sequence:
            - action: mqtt.publish
              metadata: {}
              data:
                evaluate_payload: false
                qos: 0
                retain: true
                topic: hame_energy/{{ speicher_nummer }}/CD01
                payload: "{{ trigger.payload }},end01"
        - conditions:
            - condition: trigger
              id:
                - b2500_cd13
          sequence:
            - action: mqtt.publish
              metadata: {}
              data:
                evaluate_payload: false
                qos: 0
                retain: true
                topic: hame_energy/{{ speicher_nummer }}/CD13
                payload: "{{ trigger.payload }},end13"
  mode: single
