input_button:
  b2500_package_update:
    name: B2500 Package Update starten
    icon: mdi:cloud-download

shell_command:
  run_custom_command: '/bin/bash -c "{{ command }}"'

lovelace:
   dashboards:
     b2500-dashboard:
       mode: yaml
       title: B2500-Package
       icon: mdi:view-dashboard
       show_in_sidebar: true
       filename: dashboards/b2500_dashboard.yaml
 
 
automation:
  alias: b2500_package_update
  description: Lädt Installer-Automation und führt sie aus
  triggers:
    - trigger: state
      entity_id:
        - input_button.b2500_package_update
  conditions: []
  actions:
    - data:
        command: mkdir /config/packages/b2500_package && sleep 3
      action: shell_command.run_custom_command
    - data:
        command: rm -f /config/packages/b2500_package/basicsystem.sh && sleep 5
      action: shell_command.run_custom_command
    - action: notify.persistent_notification
      metadata: {}
      data:
        message: Update gestartet
        title: b2500_package
    - data:
        command: >-
          wget -q -O /config/packages/b2500_package/basicsystem.sh
          https://raw.githubusercontent.com/Martin0475/b2500_package/main/install_scripts/basicsystem.sh &&
          sh /config/packages/b2500_package/basicsystem.sh
      action: shell_command.run_custom_command
    - action: notify.persistent_notification
      metadata: {}
      data:
        title: b2500_package
        message: yaml-Dateien neu laden
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
    - action: homeassistant.reload_all
      metadata: {}
      data: {}
  mode: single   
