fiinput_button:
  b2500pkg_update:
    name: B2500PKG Update starten
    icon: mdi:cloud-download

shell_command:
  run_custom_command: '/bin/bash -c "{{ command }}"'

lovelace:
   dashboards:
     b2500pkg-dashboard:
       mode: yaml
       title: B2500PKG
       icon: mdi:view-dashboard
       show_in_sidebar: true
       filename: dashboards/b2500pkg_dashboard.yaml
 
 
automation:
  alias: B2500PKG_update
  description: Lädt Installer-Automation und führt sie aus
  triggers:
    - trigger: state
      entity_id:
        - input_button.b2500pkg_update
  conditions: []
  actions:
    - data:
        command: mkdir /config/packages/b2500pkg && sleep 3
      action: shell_command.run_custom_command
    - data:
        command: rm -f /config/packages/b2500pkg/basicsystem.sh && sleep 5
      action: shell_command.run_custom_command
    - action: notify.persistent_notification
      metadata: {}
      data:
        message: Update gestartet
        title: B2500PKG
    - data:
        command: >-
          wget -q -O /config/packages/b2500pkg/basicsystem.sh
          https://raw.githubusercontent.com/Martin0475/b2500pkg/main/install_scripts/basicsystem.sh &&
          sh /config/packages/b2500pkg/basicsystem.sh
      action: shell_command.run_custom_command
    - action: notify.persistent_notification
      metadata: {}
      data:
        title: B2500PKG
        message: "Update fertig: yaml-Dateien werden neu geladen"
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
    - action: homeassistant.reload_all
      metadata: {}
      data: {}
  mode: single   
