automation:
  alias: b2500_package_installer
  description: ""
  triggers: []
  conditions: []
  actions:
    - data:
        message: Installer heruntergeladen!2
        title: b2500_package
      action: notify.persistent_notification
  mode: single
