input_button:
  b2500_package_update:
    name: B2500 Package Update starten
    icon: mdi:cloud-download

shell_command:
  run_custom_command: '/bin/bash -c "{{ command }}"'

automation:
    - alias: "b2500_package__Update über Button"
      description: "Lädt Installer-Automation und führt sie aus"
      
      triggers:
        - trigger: state
          entity_id:
            - input_button.b2500_package_update

      action:
        - service: shell_command.run_custom_command
          data:
            command: "rm -f /config/packages/b2500_package_installer.yaml"

        - service: shell_command.run_custom_command
          data:
            command: "wget -q -O /config/packages/b2500_package_installer.yaml https://raw.githubusercontent.com/Martin0475/b2500_package/main/b2500_package_installer.yaml"

        - action: automation.reload
          metadata: {}
          data: {}
  
        - delay:
            hours: 0
            minutes: 0
            seconds: 15

        - action: automation.trigger
          metadata: {}
          data:
            skip_condition: true
          target:
            entity_id: automation.b2500_package_installer



