automation:
  - alias: "b2500_package_installer"
    id: b2500_package_installer
    mode: single
  
    action:
     - service: notify.persistent_notification
        data:
          message: "Installer heruntergeladen!"
          title: "Info"
