input_button:
  b2500_package_update:
    name: B2500 Package Update starten
    icon: mdi:cloud-download

shell_command:
  run_custom_command: '/bin/bash -c "{{ command }}"'

automation:
  alias: b2500_package_update
  description: Lädt Installer-Automation und führt sie aus
  triggers:
    - trigger: state
      entity_id:
        - input_button.b2500_package_update
  conditions: []
  actions:
    - action: notify.persistent_notification
      metadata: {}
      data:
        message: Update gestartet
        title: b2500_package
    - data:
        command: rm -f /config/packages/b2500_package_installer.yaml && sleep 20
      action: shell_command.run_custom_command
    - data:
        command: >-
          wget -q -O /config/packages/b2500_package_installer.yaml
          https://raw.githubusercontent.com/Martin0475/b2500_package/main/b2500_package_installer.yaml
      action: shell_command.run_custom_command
    - action: automation.reload
      metadata: {}
      data: {}
    - action: notify.persistent_notification
      metadata: {}
      data:
        title: b2500_package
        message: Automationen neu laden
    - delay:
        hours: 0
        minutes: 0
        seconds: 20
        milliseconds: 0
    - action: automation.trigger
      metadata: {}
      data:
        skip_condition: true
      target:
        entity_id: automation.b2500_package_installer
  mode: single