input_text:

  b01_topic:
    name: B01 Topic
    initial: hame_energy
  b02_topic:
    name: B02 Topic
    initial: hame_energy
  b03_topic:
    name: B03 Topic
    initial: hame_energy
  b04_topic:
    name: B04 Topic
    initial: hame_energy

  b01_typ:
    name: B01 Typ
    initial: HMA-1
  b02_typ:
    name: B02 Typ
    initial: HMA-1
  b03_typ:
    name: B03 Typ
    initial: HMA-1
  b04_typ:
    name: B04 Typ
    initial: HMA-1
   
  b01_mac:
    name: B01 MAC Adresse
    initial: 0000
  b02_mac:
    name: B02 MAC Adresse
    initial: 0000
  b03_mac:
    name: B03 MAC Adresse
    initial: 0000
  b04_mac:
    name: B04 MAC Adresse
    initial: 0000

      
