automation:
  alias: Package by Martin0475 B2500_ DOD setzen
  description: |+
  
  triggers:
    - trigger: state
      entity_id:
        - input_button.b2500_dod_setzen
  conditions: []
  actions:
    - variables:
        b2500_mac: >-
          {{ states('input_text.b2500_01_mac') if
          states('input_select.speicherauswahl') == 'b2500_01' else
          states('input_text.b2500_02_mac') if
          states('input_select.speicherauswahl') == 'b2500_02' else
          states('input_text.b2500_03_mac') if
          states('input_select.speicherauswahl') == 'b2500_03' else
          states('input_text.b2500_04_mac') if
          states('input_select.speicherauswahl') == 'b2500_04' else 0 }}
        b2500_typ: >-
          {{ states('input_select.b2500_01_typ') if
          states('input_select.speicherauswahl') == 'b2500_01' else
          states('input_select.b2500_02_typ') if
          states('input_select.speicherauswahl') == 'b2500_02' else
          states('input_select.b2500_03_typ') if
          states('input_select.speicherauswahl') == 'b2500_03' else
          states('input_select.b2500_04_typ') if
          states('input_select.speicherauswahl') == 'b2500_04' else 0 }}
    - action: mqtt.publish
      metadata: {}
      data:
        evaluate_payload: false
        qos: 0
        retain: false
        topic: hame_energy/{{ b2500_typ }}/App/{{ b2500_mac }}/ctrl
        payload: cd=19,md={{ states('input_number.b2500_dod')|int }}
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
    - action: mqtt.publish
      metadata: {}
      data:
        evaluate_payload: false
        qos: 0
        retain: false
        topic: hame_energy/{{ b2500_typ }}/App/{{ b2500_mac }}/ctrl
        payload: cd=01
  mode: single
