automation:
  - alias: "Package_by_Martin0475_B2500_Installer"
    id: b2500_package_by_martin0475_installer
    mode: single
  
    action:
      - service: shell_command.b2500_download_files

      - service: notify.persistent_notification
              data:
                message: "Installer heruntergeladen!"
                title: "Info"
